name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21]
        api-level: [33, 34]   # Example: Android 13 & 14
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.java }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.java }}-

      - name: Cache Android build cache
        uses: actions/cache@v4
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-build-${{ matrix.api-level }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-build-${{ matrix.api-level }}-

      - name: Fix Gradle wrapper
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          dos2unix gradlew
          chmod +x gradlew
          test -f gradle/wrapper/gradle-wrapper.jar || { echo "gradle-wrapper.jar missing"; exit 1; }

      - name: Run Gradle build with warnings
        run: ./gradlew clean build --warning-mode all

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk-java${{ matrix.java }}-api${{ matrix.api-level }}
          path: app/build/outputs/apk/debug/app-debug.apk
