name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle wrapper and caches
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            ~/android-sdk
          key: ${{ runner.os }}-android-sdk
          restore-keys: |
            ${{ runner.os }}-android-sdk

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          if [ ! -f "cmdline-tools.zip" ]; then
            wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
            unzip -q cmdline-tools.zip -d cmdline-tools
          fi
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Fix Gradle wrapper
        run: |
          sudo apt-get install -y dos2unix
          dos2unix gradlew
          chmod +x gradlew
          test -f gradle/wrapper/gradle-wrapper.jar || { echo "gradle-wrapper.jar missing"; exit 1; }

      - name: Build Debug APK
        env:
          ANDROID_HOME: ${{ github.workspace }}/../android-sdk
          ANDROID_SDK_ROOT: ${{ github.workspace }}/../android-sdk
          PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/cmdline-tools/bin:$PATH
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
