name: Update Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  update-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Update Gradle wrapper to 9.2.0
        run: ./gradlew wrapper --gradle-version=9.2.0 --distribution-type=all

      - name: Verify wrapper update
        run: ./gradlew --version
