name: Extract ZIPs in-place

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure unzip is available
        run: sudo apt-get install -y unzip

      - name: Extract all ZIPs in-place
        run: |
          set -e
          found=0
          find . -type f -name '*.zip' | while read zipfile; do
            found=1
            dir=$(dirname "$zipfile")
            unzip -o "$zipfile" -d "$dir"
            rm "$zipfile"
          done
          if [ "$found" -eq 0 ]; then
            echo "No ZIP files found. Skipping extraction."
          fi

      - name: Configure Git and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Extracted ZIPs in-place"
            git push origin HEAD
