name: Extract ZIPs in-place

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history
          persist-credentials: false  # we’ll set our own remote

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Extract all ZIPs in-place
        run: |
          set -e
          found=0
          find . -type f -name '*.zip' | while read zipfile; do
            found=1
            dir=$(dirname "$zipfile")
            unzip -o "$zipfile" -d "$dir"
            rm "$zipfile"
          done
          if [ "$found" -eq 0 ]; then
            echo "No ZIP files found. Skipping extraction."
          fi

      - name: Commit and push extracted files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Explicitly add remote (fixes 'No such remote origin')
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          branch="${GITHUB_REF#refs/heads/}"
          git checkout -B "$branch"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Extracted ZIPs in-place"
          git pull --rebase origin "$branch" || true
          git push origin "$branch"
